version: '3.8'

services:
  web:
    build: ./dobriki
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./dobriki/:/usr/src/app/
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dobriki

volumes:
  postgres_data: