# Generated by Django 4.2.5 on 2023-09-30 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('charity', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Бюджет')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, verbose_name='Дата')),
                ('sum', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Сумма транзакции')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charity.charity', verbose_name='Фонд пожертвования')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.wallet', verbose_name='Счет')),
            ],
        ),
    ]
