# Generated by Django 4.2.5 on 2023-10-01 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitysnapshot',
            name='distance',
            field=models.FloatField(verbose_name='Расстояние'),
        ),
        migrations.AlterField(
            model_name='activitysnapshot',
            name='found',
            field=models.FloatField(verbose_name='Найденные бобры'),
        ),
        migrations.AlterField(
            model_name='activitysnapshot',
            name='kcal',
            field=models.FloatField(verbose_name='Калории'),
        ),
    ]
