# Generated by Django 4.2.5 on 2023-10-01 06:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamCompetition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название турнира')),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(verbose_name='Описание турнира')),
            ],
            options={
                'verbose_name': 'Командный турнир',
                'verbose_name_plural': 'Командные турниры',
            },
        ),
        migrations.CreateModel(
            name='UserTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название команды')),
                ('description', models.TextField(verbose_name='Описание команды')),
                ('members', models.ManyToManyField(related_name='teams', to=settings.AUTH_USER_MODEL, verbose_name='Состав')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
            },
        ),
        migrations.CreateModel(
            name='PersonalCompetition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название турнира')),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(verbose_name='Описание турнира')),
                ('participants', models.ManyToManyField(related_name='personal_competitions', to=settings.AUTH_USER_MODEL, verbose_name='Участники')),
            ],
            options={
                'verbose_name': 'Пользовательское соревнование',
                'verbose_name_plural': 'Пользовательские соревнования',
            },
        ),
    ]
