# Generated by Django 4.2.5 on 2023-09-30 14:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("competitions", "0002_teamcompetition"),
    ]

    operations = [
        migrations.AddField(
            model_name="teamcompetition",
            name="description",
            field=models.TextField(
                default=django.utils.timezone.now, verbose_name="Описание турнира"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="teamcompetition",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="teamcompetition",
            name="name",
            field=models.CharField(
                default=django.utils.timezone.now,
                max_length=255,
                verbose_name="Название турнира",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="userteam",
            name="description",
            field=models.TextField(verbose_name="Описание команды"),
        ),
        migrations.AlterField(
            model_name="userteam",
            name="name",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="Название команды"
            ),
        ),
    ]
