# Generated by Django 4.2.5 on 2023-10-01 02:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Charity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=255, verbose_name='Название организации')),
                ('name', models.CharField(max_length=255, verbose_name='Название фонда')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активность')),
                ('approved', models.BooleanField(default=False, verbose_name='Подтверждено администратором')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Почта для связи')),
                ('sum', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Сумма сбора')),
            ],
            options={
                'verbose_name': 'Фонд',
                'verbose_name_plural': 'Фонды',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Баланс')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Кошелек',
                'verbose_name_plural': 'Кошельки',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now=True, verbose_name='Дата проведения транзакции')),
                ('sum', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Cумма перевода')),
                ('fund', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='charity.charity', verbose_name='Фонд')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tra', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
            },
        ),
        migrations.CreateModel(
            name='CharitySubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='Время создания подписки')),
                ('sum', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Сумма пожертвования')),
                ('days', models.IntegerField(verbose_name='Количество дней')),
                ('charity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='charity.charity', verbose_name='Фонд')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Подписка на пожертвования',
                'verbose_name_plural': 'Подписка на пожертвования',
            },
        ),
    ]
