# Generated by Django 4.2.5 on 2023-09-30 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Charity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "organization_name",
                    models.CharField(
                        max_length=255, verbose_name="Название организации"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название фонда"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Активность"),
                ),
                (
                    "approved",
                    models.BooleanField(
                        default=False, verbose_name="Подтверждено администратором"
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="Описание"),
                ),
                (
                    "contact_email",
                    models.EmailField(max_length=254, verbose_name="Почта для связи"),
                ),
                (
                    "sum",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Сумма сбора"
                    ),
                ),
                (
                    "got_sum",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Собранная сумма"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserCharity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sum",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Собранная сумма"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время совершения пожертвования"
                    ),
                ),
                (
                    "charity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="charity.charity",
                        verbose_name="Фонд",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Связь пользователя с фондом",
                "verbose_name_plural": "Связи пользователей с фондами",
            },
        ),
        migrations.CreateModel(
            name="CharitySubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sum",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="Сумма пожертвования",
                    ),
                ),
                ("days", models.IntegerField(verbose_name="Количество дней")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время создания подписки"
                    ),
                ),
                (
                    "charity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="charity.charity",
                        verbose_name="Фонд",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Связь пользователя с фондом",
                "verbose_name_plural": "Связи пользователей с фондами",
            },
        ),
        migrations.AddField(
            model_name="charity",
            name="users",
            field=models.ManyToManyField(
                related_name="charities",
                through="charity.UserCharity",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
