# Generated by Django 4.2.5 on 2023-10-01 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charitysubscription',
            name='days',
        ),
        migrations.RemoveField(
            model_name='charitysubscription',
            name='sum',
        ),
    ]
